version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    links:
      - kafka:kafka
      - zookeeper:zookeeper
    ports:
      - "9090:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
    restart: always
  trifecta:
    image: chatu/trifecta
    container_name: trifecta
    links:
      - kafka:kafka
      - zookeeper:zookeeper
    ports:
      - "8888:8888"
    environment:
      - ZOOKEEPERS=zookeeper:2181
    restart: always
  fake-enricher:
    image: fake-enricher
    container_name: fake-enricher
    links:
      - zookeeper:zookeeper
    restart: always
